# Generated by Django 3.2.6 on 2021-11-19 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tblapis',
        ),
        migrations.DeleteModel(
            name='Tblmapperpolicyapi',
        ),
    ]
