# Generated by Django 3.2.6 on 2021-09-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tblapis',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=255, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('cloudtype', models.CharField(blank=True, db_column='CloudType', max_length=50, null=True)),
                ('conformitystatus', models.CharField(blank=True, db_column='ConformityStatus', max_length=50, null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('pic', models.TextField(blank=True, db_column='PIC', null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
            ],
            options={
                'db_table': 'tblapis',
                'managed': False,
            },
        ),
    ]
