# Generated by Django 3.2.6 on 2021-11-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tblthreatdetectionrules',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=50, null=True)),
                ('cloudtype', models.CharField(blank=True, db_column='cloudtype', max_length=45, null=True)),
                ('severity', models.CharField(blank=True, db_column='severity', max_length=45, null=True)),
                ('type', models.CharField(blank=True, db_column='type', max_length=50, null=True)),
                ('descriptions', models.TextField(blank=True, db_column='descriptions', null=True)),
                ('mitreattacktatic', models.CharField(blank=True, db_column='mitreattacktactic', max_length=45, null=True)),
                ('index', models.CharField(blank=True, db_column='index', max_length=45, null=True)),
                ('query', models.TextField(blank=True, db_column='query', null=True)),
                ('timewindow', models.CharField(blank=True, db_column='timewindow', max_length=45, null=True)),
                ('config', models.CharField(blank=True, db_column='config', max_length=45, null=True)),
                ('recommendation', models.TextField(blank=True, db_column='recommendation', null=True)),
                ('cronexpression', models.CharField(blank=True, db_column='cronexpression', max_length=50, null=True)),
                ('status', models.IntegerField(blank=True, db_column='status', null=True)),
                ('pic', models.TextField(blank=True, db_column='pic', null=True)),
                ('comment', models.TextField(blank=True, db_column='comment', null=True)),
            ],
            options={
                'db_table': 'tblthreatdetectionrules',
                'managed': False,
            },
        ),
    ]
