# Generated by Django 3.2.6 on 2021-11-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threat_detection_rules_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tblapis',
        ),
        migrations.DeleteModel(
            name='Tblmapperpolicyapi',
        ),
    ]
